---
title: "R Notebook"
output: html_notebook
---

### KEGG

```{r}


library(clusterProfiler)
library(org.Mm.eg.db)

# read dependent genelist
GF_genes <- readLines("GF_only.txt")
WT_genes <- readLines("WT_only.txt")
shared_genes <- readLines("shared.txt")

# convert genenames to ENTREZ ID
GF_entrez <- bitr(GF_genes, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
WT_entrez <- bitr(WT_genes, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
shared_entrez <- bitr(shared_genes, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")

# construct a genelist includes 3 genelists
gene_clusters <- list(
  WT = WT_entrez$ENTREZID,
  shared = shared_entrez$ENTREZID,
  GF = GF_entrez$ENTREZID
)

# KEGG
enrichKEGG_custom <- function(gene) {
  enrichKEGG(gene, organism = "mmu", keyType = "ncbi-geneid")
}

# KEGG_enrichment
ck <- compareCluster(geneCluster = gene_clusters, fun = enrichKEGG_custom)
ck <- setReadable(ck, OrgDb = org.Mm.eg.db, keyType = "ENTREZID")

# enrichment results
head(ck)

```

```{r}
ck
ck@compareClusterResult
```


```{r}
library(ggplot2)
# plot
# pdf('KEGGdotpot_WTsharedGF.pdf')
dotplot(ck) +
  scale_color_gradient(low = "blue", high = "red", name = "p.adjust") +
  theme(axis.text.y = element_text(size = 7, hjust = 1)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle("KEGG Pathway Enrichment Analysis")
#dev.off()

```

```{r}
pdf('KEGGnetwork_WTsharedGF.pdf')
cnetplot(ck)
dev.off()
```

### GO

```{r}


library(clusterProfiler)
library(org.Mm.eg.db)
library(ggplot2)

# read dependent genelist
GF_genes <- readLines("GF_only.txt")
WT_genes <- readLines("WT_only.txt")
shared_genes <- readLines("shared.txt")

# convert genenames to ENTREZ ID
GF_entrez <- bitr(GF_genes, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
WT_entrez <- bitr(WT_genes, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")
shared_entrez <- bitr(shared_genes, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Mm.eg.db")

# construct a genelist includes 3 genelists
gene_clusters <- list(
  WT = WT_entrez$ENTREZID,
  shared = shared_entrez$ENTREZID,
  GF = GF_entrez$ENTREZID
)
# GO
enrichGO_custom <- function(gene) {
  enrichGO(gene, OrgDb = org.Mm.eg.db, keyType = "ENTREZID", ont = "BP")
}

# GO enrichment
ck <- compareCluster(geneCluster = gene_clusters, fun = enrichGO_custom)
ck <- setReadable(ck, OrgDb = org.Mm.eg.db, keyType = "ENTREZID")

head(ck)

```

```{r}
pdf('GOdotplot_WTsharedKO.pdf')
dotplot(ck) +
  scale_color_gradient(low = "blue", high = "red", name = "p.adjust") +
  theme(axis.text.y = element_text(size = 8, hjust = 1)) +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle("GO Biological Process Enrichment Analysis")
dev.off()
```


```{r}

#cnetplot(ck)
pdf('GOnetwork_WTsharedKO.pdf')
cnetplot(ck, showCategory = 3)  
dev.off()

```